name: Run linting
"on":
  push:
    branches: "**"
    # don't run on tag pushes

jobs:
  run-ruff-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: "Install packages"
        run: uv pip install --system -r requirements/requirements-codestyle.txt

      - name: "Run linting"
        run: ruff check

  run-ruff-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: "Install packages"
        run: uv pip install --system -r requirements/requirements-codestyle.txt

      - name: "Check formatting"
        run: ruff format --diff

  run-mypy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: "Install packages"
        run: |
          uv pip install --system -r requirements/requirements-testing.txt

      - name: "Run Mypy"
        run: mypy .

  lint:
    needs: [run-ruff-check, run-ruff-format, run-mypy]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - name: "Check job dependencies"
        uses: actions/github-script@v4
        with:
          script: |
            const needs = ${{ toJSON(needs) }};
            const lessThanSuccess = [];
            for (const [name, { result }] of Object.entries(needs)) {
              if (result !== 'success') {
                lessThanSuccess.push(`${name} (${result})`);
              }
            }
            if (lessThanSuccess.length > 0) {
              core.setFailed(`Some of the needed jobs were less than successful: ${lessThanSuccess.join(', ')}`);
            }